services:
  webhook:
    image: ghcr.io/falbue/webhook-in-actions:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/deploy:/apps:rw
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DEPLOY_ROOT=/apps
    restart: unless-stopped
    ports:
      - "127.0.0.1:1500:8080"
